---
title: "Economia Política e Instituições"
author: "Danilo Freire"
date: "Junho e Julho de 2021"
output:
  pdf_document:
    fig_caption: yes
    latex_engine: pdflatex
    template: template.tex
  word_document: default
email: danilofreire@gmail.com
fontfamily: libertine
fontsize: 12pt
geometry: margin=1in
header-includes: \linespread{1.05}
office: Via e-mail
officehours: A qualquer hora
classroom: Online
classhours: 19:00-22:00
web: github.com/danilofreire/omma
---

# Descrição

A disciplina traz uma análise detalhada dos conceitos de instituições e de
governança em ciência política e economia. Examinaremos como as instituições
influenciam a organização social e impactam os incentivos para produção e
comércio. Veremos também uma série de exemplos históricos que ilustram não
apenas as características principais das instituições formais presentes em
democracias e autocracias, mas também como mecanismos extralegais promovem
governança em áreas onde onde o estado não pode ou não deseja atuar. 

O curso terá 18 sessões divididas em 9 dias. As aulas acontecerão nos dias 28 e
30 de junho e nos dias 05, 07, 12, 14, 19 e 21 de julho, sempre das 19:00 às
22:00 horas. As aulas terão duração de 80 minutos.

As informações referentes à disciplina estão disponíveis tanto na plataforma da
OMMA quanto em <https://github.com/danilofreire/omma>. Todos os textos, o
cronograma do curso e os slides estão inclusos no repositório, logo, fiquem à
vontade para baixar o conteúdo completo da matéria quando quiserem. Para fazer
o download, por favor, cliquem em **Code** e depois em **Download ZIP**. O
arquivo é grande, então sugiro baixá-lo no computador e não no celular. Caso
tenham quaisquer problemas, é só entrar em contato comigo via email em
[danilofreire@gmail.com](mailto:danilofreire@gmail.com).

Minha meta neste curso é que os alunos aproveitem ao máximo o conteúdo das
aulas e se sintam motivados e incluídos em todas as discussões. Assim, caso
você tenha alguma necessidade especial, não hesite em entrar em contato comigo
e farei todas as adaptações sugeridas para que você siga as aulas como achar
melhor. Além disso, dado que os alunos possuem diferentes horários de trabalho,
também me disponho a ter meus plantões de dúvidas em qualquer período ou dia da
semana. Apenas peço que, por gentileza, você me mande um email para que
possamos combinar nossa conversa virtual com alguns dias de antecedência.

# Objetivos

- Entender o que são instituições e como normas sociais permitem a coordenação de ações individuais
- Trabalhar com facilidade os conceitos políticos e econômicos necessários para o estudo do papel das instituições
- Adquirir uma visão de conjunto desta área da economia política
- Conhecer e aplicar os conceitos de normas, incentivos e mudanças institucionais que fundamentam as relações entre mercado e estado
- Familiarizar-se com a história intelectual das instituições político-econômicas e como a área se relaciona com outras disciplinas

# Avaliação

A avaliação dos alunos se dará por duas métricas. A primeira é a participação
ativa nas aulas, que contará 20% da nota final dos estudantes. Assim, é
necessário que os alunos venham com os materiais lidos e com perguntas para
serem discutidas junto com o tutor e os colegas. 

Contudo, a maior porcentagem das notas (80%) virá de um trabalho escrito com
cerca de 20 páginas a ser entregue duas semanas após o final do cronograma. O
tema é de livre escolha dentro do contexto da análise de instituições e
governança. É necessário que os alunos incluam ao menos *quatro* textos que
discutimos em alguma das aulas em sua bibliografia. A ideia é que as leituras
sirvam de base para a discussão do trabalho final e que os alunos adotem uma
perspectiva comparada dos textos, mostrando como eles se complementam ou
divergem.

Os alunos deverão trazer um resumo estendido do trabalho, com cerca de 5
páginas, no dia 18 de fevereiro. O resumo deve conter o tema do projeto de
pesquisa e uma breve introdução com o referencial teórico e metodológico que o
aluno pretende implementar no artigo. Os resumos serão distribuídos em sala
para um outro colega, o qual terá até o dia 24 de fevereiro para enviar breves
comentários sobre o projeto do autor. A sessão deste dia será toda dedicada à
discussão dos trabalhos finais, onde os estudantes poderão tirar dúvidas e
receber sugestões dos demais colegas de curso.

# Cronograma e Bibliografia

Todas as referências de leitura estão disponíveis no [repositório do curso no
GitHub](https://github.com/danilofreire/economia-politica-instituicoes-omma).
Recomenda-se que os alunos leiam os textos antes das sessões e que tragam
pontos a serem discutidos com o tutor e demais colegas. A participação em
classe é fundamental para que as aulas sejam dinâmicas e interessantes.

## Sessões 1 e 2: A Ordem Institucional (23/06)

Programa do curso. Introdução ao conceito de instituição dentro da economia
política. Considerações sobre as origens evolutivas das instituições como
resultado de ações humanas propositivas, mas não do desígnio humano. Apanhado
da história intelectual de instituições dentro do conceito de ordem.

**Leituras**:

- Norman Barry - [The Tradition of Spontaneous Order](https://github.com/danilofreire/economia-politica-instituicoes-omma/blob/master/sessoes-01-02/barry.pdf).
- Geoffrey M. Hodgson - [What Are Institutions?](https://github.com/danilofreire/economia-politica-instituicoes-omma/blob/master/sessoes-01-02/hodgson.pdf).

## Sessões 3 e 4: Diversidade Institucional I: Policentrismo (28/06)

Considerações acerca dos modelos de administração pública. Introdução aos
conceitos de mono e policentrismo institucional. Discussão sobre vantagens e
desafios de arranjos policêntricos. Federalismo e multiplicidade de
jurisdições.

**Leituras**:

- Vincent Ostrom - [The Intellectual Crisis in American Public Administration. Capítulo 1: The Crisis of Confidence](https://github.com/danilofreire/economia-politica-instituicoes-omma/blob/master/sessoes-03-04/vincent-ostrom-01.pdf) e [Capítulo 2: The Intellectual Mainstream in American Public Administration](https://github.com/danilofreire/economia-politica-instituicoes-omma/blob/master/sessoes-03-04/vincent-ostrom-02.pdf).
- Paul Dragos Aligica - [Institutional Diversity and Political Economy: The Ostroms and Beyond. Capítulo 2: Institucionalism and Polycentricity](https://github.com/danilofreire/economia-politica-instituicoes-omma/blob/master/sessoes-03-04/aligica.pdf).
- Vincent Ostrom - [Polycentricity: The Structural Basis of Self-Governing Systems](https://github.com/danilofreire/economia-politica-instituicoes-omma/blob/master/sessoes-03-04/vincent-ostrom-03.pdf).

## Sessões 5 e 6: Diversidade Institucional II: IAD Framework (30/06)

Considerações sobre o trabalho de Elinor Ostrom. Introdução ao Framework de
Análise e Desenvolvimento Institutional. Aplicações teóricas e práticas.

**Leituras**:

- Elinor Ostrom - [The Three Worlds of Action](https://github.com/danilofreire/economia-politica-instituicoes-omma/blob/master/sessoes-05-06/elinor-ostrom-01.pdf).
- Elinor Ostrom - [An Agenda for the Study of Institutions](https://github.com/danilofreire/economia-politica-instituicoes-omma/blob/master/sessoes-05-06/elinor-ostrom-02.pdf).

## Sessões 7 e 8: Instituições no Contratualismo (05/07)

Como uma teoria institucional pode derivar autoridade e legitimidade a partir
do consentimento dos governados. A forma e o conteúdo do consentimento e a
ideia de contrato e de acordos mutuamente benéficos. A origem da força
normativa e da possibilidade de reconhecimento e execução de instituições. A
ideia de justiça derivada do contrato social. Véu de ignorância e suas
consequências normativas.

**Leituras**:

- Thomas Hobbes - [Leviathan. Capítulos 13, 14, 17, 18, 21 e 29](https://github.com/danilofreire/economia-politica-instituicoes-omma/blob/master/sessoes-07-08/hobbes.pdf).
- John Rawls - [A Theory of Justice. Trechos selecionados](https://github.com/danilofreire/economia-politica-instituicoes-omma/blob/master/sessoes-07-08/rawls.pdf).

## Sessões 9 e 10: Violência, Democracias e Ditaduras (07/07)

Uso da força e ordem social. Bens públicos e redistribuição econômica. A
motivação de governantes e governados na construção institucional. A
possibilidade de se planejar coordenação econômica a partir de um desenho
institucional. Efeitos de longo prazo dos regimes políticos. 

**Leituras**:

- Mancur Olson - [Dictatorship, Democracy, and Development](https://github.com/danilofreire/economia-politica-instituicoes-omma/blob/master/sessoes-09-10/olson.pdf).
- Douglass North, John Wallis, Barry Weingast - [Violence and the Rise of Open-Access Orders](https://github.com/danilofreire/economia-politica-instituicoes-omma/blob/master/sessoes-09-10/north.pdf).

## Sessões 11 e 12: Instituições no Ocidente (12/07)

Uma breve história das origens concretas do estabelecimento institucional no
Ocidente. O papel da Igreja Católica no direito e na ideia de soberania
estatal. Comércio atlântico e crescimento econômico. Impactos de longo prazo no
desenvolvimento político e social do Ocidente.

**Lembrete**: Entregar um resumo ampliado, com cerca de 5 páginas, com uma
breve introdução e as referências teóricas e metodológicas que embasarão o
trabalho final.

**Leituras**:

- Harold Berman - [Law and Revolution (extratos)](https://github.com/danilofreire/economia-politica-instituicoes-omma/blob/master/sessoes-11-12/berman.pdf).
- Daron Acemoglu, Simon Johnson e James Robinson - [The Rise of Europe: Atlantic Trade, Institutional Change, and Economic Growth](https://github.com/danilofreire/economia-politica-instituicoes-omma/blob/master/sessoes-11-12/acemoglu.pdf).

## Sessões 13 e 14: Instituições no Terceiro Mundo e o Caso Islâmico (14/07)

Relação entre a teoria do capital e a teoria institucional. O papel das
instituições no desenvolvimento econômico histórico. Como ocorre a destruição
criadora em sociedades em desenvolvimento e de que maneira a coordenação
econômica possibilitada pelas instituições fortalece ou previne o crescimento
econômico. Estudo da emergência de instituições econômicas no mundo islâmico e
seus efeitos no desenvolvimento regional. 

**Leituras**:

- Hernando de Soto - [The Mystery of Capital. Capítulos 1-3](https://github.com/danilofreire/economia-politica-instituicoes-omma/blob/master/sessoes-13-14/desoto.pdf).
- Timur Kuran - [The Puzzle of the Middle East’s Economic Underdevelopment](https://github.com/danilofreire/economia-politica-instituicoes-omma/blob/master/sessoes-13-14/kuran-01.pdf). 
- Timur Kuran - [The Economic Impact of Islamism](https://github.com/danilofreire/economia-politica-instituicoes-omma/blob/master/sessoes-13-14/kuran-02.pdf).

## Sessões 15 e 16: Discussão dos Trabalhos Finais (19/07)

A sessão será dedicada à discussão dos trabalhos finais. Não há leituras
obrigatórias para esta data.

**Lembrete**: Trazer comentários acerca das propostas dos colegas.

## Sessões 17 e 18: Instituições Além do Estado: Organizações Ilegais (21/07)

Como instituições produzidos de forma privada e regulamentos econômicos privados podem ser exequíveis e eficazes. Casos históricos de instituições de governança privada demonstrando sua emergência e explicando seu funcionamento.

**Leituras**:

- David Skarbek e Danilo Freire - [Prison Gangs](https://github.com/danilofreire/economia-politica-instituicoes-omma/blob/master/sessoes-17-18/skarbek-freire.pdf).
- David Skarbek - [Covenants without the Sword? Comparing Prison Self-Governance Globally](https://github.com/danilofreire/economia-politica-instituicoes-omma/blob/master/sessoes-17-18/skarbek.pdf) (Leitura recomendada).
- Danilo Freire - [Beasts of Prey or Rational Animals? Private Governance in Brazil's _Jogo do Bicho_](https://github.com/danilofreire/economia-politica-instituicoes-omma/blob/master/sessoes-17-18/freire.pdf).
